CREATE TABLE NumberPlate(acronym varchar PRIMARY KEY,
						 district varchar
						 );	

INSERT INTO NumberPlate(acronym,district) 
Values 
('0','Diplomatisches Corps'),
('A','Augsburg'),
('AA','Aalen Ostalbkreis'),
('AB','Aschaffenburg'),
('ABG','Altenburger Land'),
('AC','Aachen'),
('AE','Auerbach'),
('AIC','Aichach-Friedberg'),
('AK','Altenkirchen/Westerwald'),
('AM','Amberg'),
('AN','Ansbach'),
('ANA','Annaberg'),
('ANG','Angermünde'),
('ANK','Anklam'),
('AÖ','Altötting'),
('AP','Apolda - Weimarer Land'),
('APD','Apolda'),
('ARN','Arnstadt'),
('ART','Artern'),
('AS','Amberg-Sulzbach'),
('ASL','Aschersleben'),
('ASZ','Aue-Schwarzenberg'),
('AT','Altentreptow'),
('AU','Aue'),
('AUR','Aurich'),
('AW','Bad Neuenahr-Ahrweiler'),
('AZ','Alzey-Worms'),
('AZE','Anhalt-Zerbst'),
('B','Berlin'),
('BA','Bamberg'),
('BAD','Baden-Baden'),
('BAR','Barnim'),
('BB','Böblingen'),
('BBG','Bernburg'),
('BBL','Brandenburg Landesregierung und Landtag'),
('BC','Biberach/Riß'),
('BD','Bundestag, Bundesrat, Bundesregierung'),
('BED','Brand-Erbisdorf'),
('BEL','Belzig'),
('BER','Bernau bei Berlin'),
('BGL','Berchtesgadener Land'),
('BI','Bielefeld'),
('BIR','Birkenfeld/Nahe und Idar-Oberstein'),
('BIT','Bitburg-Prüm'),
('BIW','Bischofswerda'),
('BL','Zollernalbkreis / Balingen'),
('BLK','Burgenlandkreis'),
('BM','Erftkreis / Bergheim'),
('BN','Bonn'),
('BNA','Borna'),
('BO','Bochum'),
('BÖ','Bördekreis-Oschersleben'),
('BOR','Borken / Ahaus'),
('BOT','Bottrop'),
('BP','Bundespolizei'),
('BRA','Wesermarsch / Brake'),
('BRB','Brandenburg'),
('BRG','Burg'),
('BS','Braunschweig'),
('BSK','Beeskow'),
('BT','Bayreuth'),
('BTF','Bitterfeld'),
('BÜS','Büsingen am Hochrhein'),
('BÜZ','Bützow'),
('BW','Bundes-Wasser- und Schiffahrtsverwaltung'),
('BWL','Baden-Württemberg Landesregierung und Landtag'),
('BYL','Bayern Landesregierung und Landtag'),
('BZ','Bautzen'),
('C','Chemnitz'),
('CA','Calau'),
('CB','Cottbus'),
('CE','Celle'),
('CHA','Cham/Oberpfalz'),
('CLP','Cloppenburg'),
('CO','Coburg'),
('COC','Cochem-Zell/Mosel'),
('COE','Coesfeld/Westfalen'),
('CUX','Cuxhaven'),
('CW','Calw'),
('D','Düsseldorf'),
('DA','Darmstadt-Dieburg'),
('DAH','Dachau'),
('DAN','Lüchow-Dannenberg'),
('DAU','Daun'),
('DB','Deutsche Bahn'),
('DBR','Bad Doberan'),
('DD','Dresden'),
('DE','Dessau'),
('DEG','Deggendorf'),
('DEL','Delmenhorst'),
('DGF','Dingolfing-Landau'),
('DH','Diepholz-Syke'),
('DL','Döbeln'),
('DLG','Dillingen/Donau'),
('DM','Demmin'),
('DN','Düren'),
('DO','Dortmund'),
('DON','Donau-Ries / Donauwörth'),
('DS','Dahme-Spreewald'),
('DU','Duisburg'),
('DÜW','Bad Dürkheim / Neustadt/Weinstraße'),
('DW','Dippoldiswalde-Weißeritzkreis'),
('DZ','Delitzsch'),
('E','Essen'),
('EA','Eisenach'),
('EB','Eilenburg'),
('EBE','Ebersberg'),
('ED','Erding'),
('EE','Elbe-Elster'),
('EF','Erfurt'),
('EH','Eisenhüttenstadt'),
('EI','Eichstätt'),
('EIC','Eichsfeld'),
('EIL','Eisleben'),
('EIS','Eisenberg'),
('EL','Emsland / Meppen'),
('EM','Emmendingen'),
('EMD','Emden'),
('EMS','Rhein-Lahn-Kreis / Bad Ems'),
('EN','Ennepe-Ruhr-Kreis / Schwelm'),
('ER','Erlangen/Stadt'),
('ERB','Odenwaldkreis / Erbach'),
('ERH','Erlangen-Höchstadt'),
('ES','Esslingen/Neckar'),
('ESA','Eisenach'),
('ESW','Werra-Meißner-Kreis / Eschwege'),
('EU','Euskirchen'),
('EW','Eberswalde'),
('F','Frankfurt/Main'),
('FB','Wetteraukreis / Friedberg'),
('FD','Fulda'),
('FDS','Freudenstadt'),
('FF','Frankfurt/Oder'),
('FFB','Fürstenfeldbruck'),
('FG','Freiberg/Sachsen'),
('FI','Finsterwalde'),
('FL','Flensburg'),
('FLÖ','Flöha'),
('FN','Bodenseekreis / Friedrichshafen'),
('FO','Forchheim'),
('FOR','Forst'),
('FR','Freiburg/Breisgau'),
('FRG','Freyung-Grafenau'),
('FRI','Friesland / Jever'),
('FRW','Bad Freienwalde'),
('FS','Freising'),
('FT','Frankenthal/Pfalz'),
('FTL','Freital'),
('FÜ','Fürth'),
('FW','Fürstenwalde'),
('G','Gera'),
('GA','Gardelegen'),
('GAP','Garmisch-Partenkirchen'),
('GC','Glauchau - Chemnitzer Land'),
('GDB','Gadebusch'),
('GE','Gelsenkirchen'),
('GER','Germersheim'),
('GF','Gifhorn'),
('GG','Groß-Gerau'),
('GHA','Geithain'),
('GHC','Gräfenhainichen'),
('GI','Gießen'),
('GL','Rheinisch-Bergischer Kreis / Bergisch Gladbach'),
('GM','Oberbergischer Kreis / Gummersbach'),
('GMN','Grimmen'),
('GNT','Genthin'),
('GÖ','Göttingen'),
('GP','Göppingen'),
('GR','Görlitz'),
('GRH','Grossenhain'),
('GRM','Grimma'),
('GRS','Gransee'),
('GRZ','Greiz'),
('GS','Goslar'),
('GT','Gütersloh / Rheda-Wiedenbrück'),
('GTH','Gotha'),
('GÜ','Güstrow'),
('GUB','Guben'),
('GVM','Grevesmühlen'),
('GW','Greifswald/Landkreis'),
('GZ','Günzburg'),
('H','Hannover'),
('HA','Hagen/Westfalen'),
('HAL','Halle/Saale'),
('HAM','Hamm/Westfalen'),
('HAS','Haßberge / Haßfurt'),
('HB','Hansestadt Bremen und Bremerhaven'),
('HBN','Hildburghausen'),
('HBS','Halberstadt'),
('HC','Hainichen'),
('HD','Rhein-Neckar-Kreis und Heidelberg'),
('HDH','Heidenheim/Brenz'),
('HDL','Haldensleben'),
('HE','Helmstedt'),
('HEF','Bad Hersfeld-Rotenburg'),
('HEI','Dithmarschen / Heide/Holstein'),
('HEL','Hessen Landesregierung und Landtag'),
('HER','Herne'),
('HET','Hettstedt'),
('HF','Herford / Kirchlengern'),
('HG','Hochtaunuskreis / Bad Homburg v.d.H.'),
('HGN','Hagenow'),
('HGW','Hansestadt Greifswald'),
('HH','Hansestadt Hamburg'),
('HHM','Hohenmölsen'),
('HI','Hildesheim'),
('HIG','Heiligenstadt'),
('HL','Hansestadt Lübeck'),
('HM','Hameln-Pyrmont'),
('HN','Heilbronn/Neckar'),
('HO','Hof/Saale'),
('HOL','Holzminden'),
('HOM','Saar-Pfalz-Kreis / Homburg/Saar'),
('HOT','Hohenstein-Ernstthal'),
('HP','Bergstraße / Heppenheim'),
('HR','Schwalm-Eder-Kreis / Homberg'),
('HRO','Hansestadt Rostock'),
('HS','Heinsberg'),
('HSK','Hochsauerlandkreis / Meschede'),
('HST','Hansestadt Stralsund'),
('HU','Hanau'),
('HV','Havelberg'),
('HVL','Havelland'),
('HWI','Hansestadt Wismar'),
('HX','Höxter'),
('HY','Hoyerswerda'),
('HZ','Herzberg'),
('IGB','St. Ingbert'),
('IK','Ilm-Kreis'),
('IL','Ilmenau'),
('IN','Ingolstadt/Donau'),
('IZ','Itzehoe'),
('J','Jena'),
('JB','Jüterbog'),
('JE','Jessen'),
('JL','Jerichower Land'),
('K','Köln'),
('KA','Karlsruhe'),
('KB','Waldeck-Frankenberg / Korbach'),
('KC','Kronach'),
('KE','Kempten/Allgäu'),
('KEH','Kelheim'),
('KF','Kaufbeuren'),
('KG','Bad Kissingen'),
('KH','Bad Kreuznach'),
('KI','Kiel'),
('KIB','Donnersberg-Kreis / Kirchheimbolanden'),
('KL','Kaiserslautern'),
('KLE','Kleve'),
('KLZ','Klötze'),
('KM','Kamenz'),
('KN','Konstanz'),
('KO','Koblenz'),
('KÖT','Köthen'),
('KR','Krefeld'),
('KS','Kassel'),
('KT','Kitzingen'),
('KU','Kulmbach'),
('KÜN','Hohenlohe-Kreis / Künzelsau'),
('KUS','Kusel'),
('KW','Königs-Wusterhausen'),
('KY','Kyritz'),
('KYF','Kyffhäuserkreis'),
('L','Leipzig'),
('LA','Landshut'),
('LAU','Nürnberger Land / Lauf/Pegnitz'),
('LB','Ludwigsburg'),
('LBS','Lobenstein'),
('LBZ','Lübz'),
('LC','Luckau'),
('LD','Landau/Pfalz'),
('LDK','Lahn-Dill-Kreis / Wetzlar'),
('LDS','Dahme-Spreewald'),
('LER','Leer/Ostfriesland'),
('LEV','Leverkusen'),
('LG','Lüneburg'),
('LI','Lindau/Bodensee'),
('LIB','Bad Liebenwerda'),
('LIF','Lichtenfels'),
('LIP','Lippe / Detmold'),
('LL','Landsberg/Lech'),
('LM','Limburg-Weilburg/Lahn'),
('LN','Lübben'),
('LÖ','Lörrach'),
('LÖB','Löbau'),
('LOS','Oder-Spree-Kreis Beeskow'),
('LSA','Sachsen-Anhalt Landesregierung und Landtag'),
('LSN','Sachsen Landesregierung und Landtag'),
('LSZ','Bad Langensalza'),
('LU','Ludwigshafen/Rhein'),
('LUK','Luckenwalde'),
('LWL','Ludwigslust'),
('M','München'),
('MA','Mannheim'),
('MAB','Marienberg'),
('MB','Miesbach'),
('MC','Malchin'),
('MD','Magdeburg'),
('ME','Mettmann'),
('MEI','Meißen'),
('MEK','Mittlerer Erzgebirgskreis'),
('MER','Merseburg'),
('MG','Mönchengladbach'),
('MGN','Meiningen'),
('MH','Mülheim/Ruhr'),
('MHL','Mühlhausen'),
('MI','Minden-Lübbecke/Westfalen'),
('MIL','Miltenberg'),
('MK','Märkischer Kreis / Lüdenscheid'),
('MKK','Main-Kinzig-Kreis'),
('ML','Mansfelder Land'),
('MM','Memmingen'),
('MN','Unterallgäu / Mindelheim'),
('MOL','Märkisch-Oderland'),
('MOS','Neckar-Odenwald-Kreis / Mosbach'),
('MQ','Merseburg-Querfurt'),
('MR','Marburg-Biedenkopf/Lahn'),
('MS','Münster/Westfalen'),
('MSP','Main-Spessart-Kreis / Karlstadt'),
('MST','Mecklenburg-Strelitz'),
('MTK','Main-Taunus-Kreis / Hofheim'),
('MÜ','Mühldorf am Inn'),
('MÜR','Müritz'),
('MVL','Mecklenburg-Vorpommern Landesregierung und Landtag'),
('MW','Mittweida'),
('MYK','Mayen-Koblenz'),
('MZ','Mainz-Bingen und Mainz'),
('MZG','Merzig-Wadern'),
('N','Nürnberg'),
('NAU','Nauen'),
('NB','Neubrandenburg'),
('ND','Neuburg-Schrobenhausen/Donau'),
('NDH','Nordhausen'),
('NE','Neuss'),
('NEA','Neustadt-Bad Windsheim/Aisch'),
('NEB','Nebra/Unstrut'),
('NES','Rhön-Grabfeld / Bad Neustadt/Saale'),
('NEW','Neustadt/Waldnaab'),
('NF','Nordfriesland / Husum'),
('NH','Neuhaus/Rennsteig'),
('NI','Nienburg/Weser'),
('NK','Neunkirchen/Saar'),
('NL','Niedersachsen Landesregierung und Landtag'),
('NM','Neumarkt/Oberpfalz'),
('NMB','Naumburg/Saale'),
('NMS','Neumünster'),
('NOH','Grafschaft Bentheim / Nordhorn'),
('NOL','Niederschlesischer Oberlausitzkreis'),
('NOM','Northeim'),
('NP','Neuruppin'),
('NR','Neuwied/Rhein'),
('NRW','Nordrhein-Westfalen Landesregierung und Landtag'),
('NU','Neu-Ulm'),
('NVP','Nordvorpommern'),
('NW','Neustadt/Weinstraße'),
('NWM','Nordwestmecklenburg'),
('NY','Niesky'),
('NZ','Neustrelitz'),
('OA','Oberallgäu / Sonthofen'),
('OAL','Ostallgäu / Marktoberdorf'),
('OB','Oberhausen/Rheinland'),
('OBG','Osterburg'),
('OC','Oschersleben'),
('OD','Stormarn / Bad Oldesloe'),
('OE','Olpe'),
('OF','Offenbach/Main'),
('OG','Ortenaukreis / Offenburg'),
('OH','Ostholstein / Eutin'),
('OHA','Osterode/Harz'),
('OHV','Oranienburg Oberhavel'),
('OHZ','Osterholz-Scharmbeck'),
('OK','Ohre-Kreis'),
('OL','Oldenburg'),
('OPR','Ostprignitz-Ruppin'),
('OR','Oranienburg'),
('OS','Osnabrück'),
('OSL','Senftenberg - Oberspreewald-Lausitz'),
('OVL','Obervogtland / Klingenthal und Ölsnitz'),
('OVP','Ostvorpommern'),
('OZ','Oschatz'),
('P','Potsdam'),
('PA','Passau'),
('PAF','Pfaffenhofen/Ilm'),
('PAN','Rottal-Inn / Pfarrkirchen'),
('PB','Paderborn'),
('PCH','Parchim'),
('PE','Peine'),
('PER','Perleberg'),
('PF','Enzkreis und Pforzheim'),
('PI','Pinneberg'),
('PIR','Pirna - Sächsische Schweiz'),
('PK','Pritzwalk'),
('PL','Plauen'),
('PLÖ','Plön/Holstein'),
('PM','Belzig - Potsdam-Mittelmark'),
('PN','Pössneck'),
('PR','Prignitz / Perleberg'),
('PS','Pirmasens'),
('PW','Pasewalk'),
('PZ','Prenzlau'),
('QFT','Querfurt'),
('QLB','Quedlinburg'),
('R','Regensburg'),
('RA','Rastatt'),
('RC','Reichenbach/Vogtland'),
('RD','Rendsburg-Eckernförde'),
('RDG','Ribnitz-Damgarten'),
('RE','Recklinghausen / Marl'),
('REG','Regen'),
('RG','Riesa-Großenhain'),
('RH','Roth/Rednitz'),
('RIE','Riesa'),
('RL','Rochlitz'),
('RM','Röbel/Müritz'),
('RN','Rathenow'),
('RO','Rosenheim'),
('ROS','Rostock/Landkreis'),
('ROW','Rotenburg/Wümme'),
('RP','Rhein-Pfalz-Kreis'),
('RPL','Rheinland-Pfalz Landesregierung und Landtag'),
('RS','Remscheid'),
('RSL','Rosslau/Elbe'),
('RT','Reutlingen'),
('RU','Rudolstadt'),
('RÜD','Rheingau-Taunus-Kreis / Rüdesheim'),
('RÜG','Rügen / Bergen'),
('RV','Ravensburg'),
('RW','Rottweil'),
('RZ','Herzogtum Lauenburg / Ratzeburg'),
('S','Stuttgart'),
('SAD','Schwandorf'),
('SAL','Saarland Landesregierung und Landtag'),
('SAW','Altmarkkreis - Salzwedel'),
('SB','Saarbrücken'),
('SBG','Strasburg'),
('SBK','Schönebeck/Elbe'),
('SC','Schwabach'),
('SCZ','Schleiz'),
('SDH','Sondershausen'),
('SDL','Stendal'),
('SDT','Schwedt/Oder'),
('SE','Bad Segeberg'),
('SEB','Sebnitz'),
('SEE','Seelow'),
('SFA','Soltau-Fallingbostel'),
('SFB','Senftenberg'),
('SFT','Stassfurt'),
('SG','Solingen'),
('SGH','Sangerhausen'),
('SH','Schleswig-Holstein Landesregierung und Landtag'),
('SHA','Schwäbisch Hall'),
('SHG','Schaumburg / Stadthagen'),
('SHK','Saale-Holzlandkreis'),
('SHL','Suhl'),
('SI','Siegen-Wittgenstein'),
('SIG','Sigmaringen'),
('SIM','Rhein-Hunsrück-Kreis / Simmern'),
('SK','Saalkreis / Halle'),
('SL','Schleswig-Flensburg'),
('SLF','Saalfeld-Rudolstadt'),
('SLN','Schmölln'),
('SLS','Saarlouis'),
('SLZ','Bad Salzungen'),
('SM','Schmalkalden-Meiningen'),
('SN','Schwerin'),
('SO','Soest'),
('SOK','Saale-Orla-Kreis'),
('SÖM','Sömmerda'),
('SON','Sonneberg'),
('SP','Speyer'),
('SPB','Spremberg'),
('SPN','Spree-Neiße'),
('SR','Straubing-Bogen'),
('SRB','Strausberg'),
('SRO','Stadtroda'),
('ST','Steinfurt'),
('STA','Starnberg'),
('STB','Sternberg'),
('STD','Stade'),
('STL','Stollberg'),
('SU','Rhein-Sieg-Kreis / Siegburg'),
('SÜW','Südl. Weinstraße / Landau'),
('SW','Schweinfurt'),
('SZ','Salzgitter'),
('SZB','Schwarzenberg'),
('TBB','Main-Tauber-Kreis / Tauberbischofsheim'),
('TET','Teterow'),
('TF','Teltow-Fläming'),
('TG','Torgau'),
('THL','Thüringen Landesregierung und Landtag'),
('THW','Technisches Hilfswerk'),
('TIR','Tirschenreuth'),
('TO','Torgau-Oschatz'),
('TÖL','Bad Tölz-Wolfratshausen'),
('TP','Templin/Uckermark'),
('TR','Trier-Saarburg'),
('TS','Traunstein'),
('TÜ','Tübingen'),
('TUT','Tuttlingen'),
('UE','Uelzen'),
('UEM','Ueckermünde'),
('UER','Uecker-Randow'),
('UH','Unstrut-Hainich-Kreis'),
('UL','Alb-Donau-Kreis und Ulm'),
('UM','Uckermark'),
('UN','Unna/Westfalen'),
('V','Vogtlandkreis - Plauen'),
('VB','Vogelsbergkreis / Lauterbach'),
('VEC','Vechta'),
('VER','Verden/Aller'),
('VIE','Viersen'),
('VK','Völklingen'),
('VS','Schwarzwald-Baar-Kreis / Villingen-Schwenningen'),
('W','Wuppertal'),
('WAF','Warendorf'),
('WAK','Wartburgkreis'),
('WB','Wittenberg'),
('WBS','Worbis'),
('WDA','Werdau'),
('WE','Weimar'),
('WEN','Weiden/Oberpfalz'),
('WES','Wesel / Mörs'),
('WF','Wolfenbüttel'),
('WHV','Wilhelmshaven'),
('WI','Wiesbaden'),
('WIL','Bernkastel-Wittlich/Mosel'),
('WIS','Wismar/Landkreis'),
('WK','Wittstock'),
('WL','Harburg / Winsen/Luhe'),
('WLG','Wolgast/Usedom'),
('WM','Weilheim-Schongau/Oberbayern'),
('WMS','Wolmirstedt'),
('WN','Rems-Murr-Kreis / Waiblingen'),
('WND','St. Wendel'),
('WO','Worms'),
('WOB','Wolfsburg'),
('WR','Wernigerode'),
('WRN','Waren/Müritz'),
('WSF','Weißenfels'),
('WST','Ammerland / Westerstede'),
('WSW','Weißwasser'),
('WT','Waldshut-Tiengen'),
('WTM','Wittmund'),
('WÜ','Würzburg'),
('WUG','Weißenburg-Gunzenhausen'),
('WUN','Wunsiedel'),
('WUR','Wurzen'),
('WW','Westerwald / Montabaur'),
('WZL','Wanzleben'),
('X','Bundeswehr für NATO-Hauptquartiere'),
('Y','Bundeswehr'),
('Z','Zwickauer Land'),
('ZE','Zerbst'),
('ZI','Sächsischer Oberlausitzkreis Zittau'),
('ZP','Zschopau'),
('ZR','Zeulenroda'),
('ZS','Zossen'),
('ZW','Zweibrücken'),
('ZZ','Zeitz');